[[plugins]]
repo = 'Shougo/dein.vim'

# color-theme
[[plugins]]
repo = 'altercation/vim-colors-solarized'

# Vim上でGit操作を行うやつ
[[plugins]]
repo = 'tpope/vim-fugitive'

# GitHub Extension
[[plugins]]
repo = 'tpope/vim-rhubarb'

# Status bar
[[plugins]]
repo = 'itchyny/lightline.vim'

# ファイルエクスプローラー
[[plugins]]
repo = 'Shougo/defx.nvim'
depends = ['defx-git', 'defx-icons']
hook_add = """
source ~/.config/nvim/plugins/defx.rc.vim
"""

# defxで使うアイコンフォント
[[plugins]]
repo = 'kristijanhusak/defx-icons'

# defxでGit statusを表示する
[[plugins]]
repo = 'kristijanhusak/defx-git'

# ファイル検索など
[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = """
source ~/.config/nvim/plugins/denite.rc.vim
"""

# 非同期処理用(Vimスクリプトで使う)
[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

# バッファ(開いたファイル)を簡単に行き来できる
[[plugins]]
repo = 'jlanzarotta/bufexplorer'

# プログラミング関連のアイコンを追加する(他のプラグインがこれに依存してたりする)
[[plugins]]
repo = 'ryanoasis/vim-devicons'

# 括弧の置換など
# http://vimblog.hatenablog.com/entry/vim_plugin_surround_vim
[[plugins]]
repo = 'tpope/vim-surround'

# 他のプラグインがこれに依存してたりする
[[plugins]]
# Yet Another Remote Plugin Framework for Neovim
repo = 'roxma/nvim-yarp'
if = '''!has('nvim')'''

# 他のプラグインがこれに依存してたりする
[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
if = '''!has('nvim')'''

# 他のプラグインがこれに依存してたりする
[[plugins]]
repo = 'neovim/python-client'
if = '''!has('nvim')'''

# LSP(Language Server Protocol)
[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_add = """
source ~/.config/nvim/plugins/lsp.rc.vim
"""
[[plugins]]
repo = 'mattn/vim-lsp-settings'

# LSP AutoCompletion
[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
if !has('nvim')
  call dein#add('roxma/nvim-yarp')
  call dein#add('roxma/vim-hug-neovim-rpc')
endif
let g:deoplete#enable_at_startup = 1
'''
[[plugins]]
repo = 'lighttiger2505/deoplete-vim-lsp'

# Snipette
[[plugins]]
repo = 'Shougo/neosnippet.vim'
[[plugins]]
repo = 'Shougo/neosnippet-snippets'

# Japanese Vim Help
[[plugins]]
repo = 'vim-jp/vimdoc-ja'

# Rainbow brackets
[[plugins]]
repo = 'luochen1990/rainbow'
hook_add = '''
    let g:rainbow_active = 1
'''

# Multi cursor
[[plugins]]
repo = 'mg979/vim-visual-multi'
rev = 'master'

# Terminal Plugin
[[plugins]]
repo = "Shougo/deol.nvim"
hook_add = '''
" 【Ctrl + o】 float windowでターミナルを表示
nnoremap <silent><Space>T :<C-u>Deol -split=floating<CR>
" 【ESC】 ターミナルモードから抜ける
tnoremap <ESC>   <C-\><C-n>
'''

# window controller
# Ctrl-E でウィンドウの高さや幅を変更出来る
[[plugins]]
repo = "simeji/winresizer"
