###########################
# 昔使ってたdein.tomlです #
###########################
[[plugins]]
# パッケージ管理
repo = 'Shougo/dein.vim'

## カラースキーマ
#[[plugins]]
#repo = 'ajmwagar/vim-deus'

# カラースキーマ
[[plugins]]
repo = 'cocopon/iceberg.vim'

# カラースキーマ
#[[plugins]]
#repo = 'tomasr/molokai'

# Status bar
[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

#入力補完
[[plugins]]
repo = 'Shougo/neocomplcache'

# スニペットの補完機能
[[plugins]]
repo = 'Shougo/neosnippet'

# スニペット集
[[plugins]]
repo = 'Shougo/neosnippet-snippets'


[[plugins]]
repo = 'junegunn/vim-easy-align'

#(,) complete
[[plugins]]
repo = 'cohama/lexima.vim'

# Display matched number
[[plugins]]
repo = 'osyo-manga/vim-anzu'

# f search extention
[[plugins]]
repo = 'rhysd/clever-f.vim'

# Hilight copied or yanked part
[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'haya14busa/vim-operator-flashy'

# Mattn's html completion
[[plugins]]
repo = 'mattn/emmet-vim'

# Tagbar: definiton of class, method,...
[[plugins]]
repo = 'majutsushi/tagbar'

# auto clone ", ', ...
[[plugins]]
repo = 'Townk/vim-autoclose'

# Visualize indent space
[[plugins]]
repo = 'Yggdroot/indentLine'

# Hilight white space
# Delete white space by ":FixWhite..."
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

# Git vim plugins
[[plugins]]
repo = 'tpope/vim-fugitive'
[[plugins]]
repo = 'airblade/vim-gitgutter'

# File tree
[[plugins]]
repo = 'scrooloose/nerdtree'

# Async linter
# Grammar check
[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'cannot-fly-pig/vim-atcoder'

# Japanese Vim Help
[[plugins]]
repo = 'vim-jp/vimdoc-ja'

# 置換のプレビュー
[[plugins]]
repo = 'markonm/traces.vim'
